#-------------------------------
# Site Settings
title: Wayne
description: I am a dedicated computer science student passionate about machine learning
logo: "/images/logo.svg" # You can add own logo. For example "/images/logo.svg".
logo_dark: "/images/logo-dark.svg"
color_scheme: dark # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: "Home"
      url: "/"
    - title: "Projects"
      url: "/projects/"
    - title: "Posts"
      url: "/posts/"
    # - title: "Resources"
    #   submenu:
    #   - url: "/posts/the-psychology-of-mobile-app-colors-influencing-user-perception"
    #     title: "News"
    #   - url: "/posts/gamifying-the-user-experience-strategies-beyond-mobile-games"
    #     title: "Games"
    #   - url: "/posts/harmonizing-aesthetics-and-functionality-in-ux-ui-mobile-design"
    #     title: "Mobile"
    #   - url: "/elements/"
    #     title: "Elements"
    - title: "About Me"
      url: "/about/"

# Call to action button
cta_button:
  enable: true
  cta_button_link: '/contact/'
  cta_button_text: Get in touch


#-------------------------------
# Author Settings
author:
  author_name: "Wayne Simmons"
  author_avatar: "/images/01-1.jpg"


#-------------------------------
# Hero Settings
hero:
  enable: true
  hero_title: I am a dedicated computer science student passionate about machine learning.
  hero_description: Leveraging my experience in machine learning and software development, I work on building practical solutions that turn complex data into meaningful results. I'm always excited to collaborate on projects that push ideas beyond theory and into real-world impact.

# Hero Logos
hero_logos:
  enable: false

hero_logo_image:
  - alt: "Apple Logo"
    image: "/images/apple.svg"

  - alt: "Adobe Logo"
    image: "/images/adobe.svg"

  - alt: "HP Logo"
    image: "/images/hp.svg"

  - alt: "Netlify Logo"
    image: "/images/netlify.svg"

  - alt: "Dropbox Logo"
    image: "/images/dropbox.svg"

  - alt: "EA Logo"
    image: "/images/ea.svg"

  - alt: "Chrome Logo"
    image: "/images/chrome.svg"


#-------------------------------
# Slider Featured Settings
featured:
  enable: true
  featured_title: Selected Work


#-------------------------------
# Projects Section Settings
projects:
  enable: true
  projects_title: Recent Work
  projects_description:


#-------------------------------
# Testimonials Section Settings
testimonials:
  enable: false
  testimonials_intro: Don't take my word for it
  testimonials_title: See what our happy clients say...
  testimonials_info: Join over <b>10K+</b> Prefessionals

testimonial_items:
  - name: "Martin Vetrovs"
    image: "/images/client-1.jpg"
    designation: "Data Scientist"
    title: "Incredible attention to detail"
    content : "The incredible attention to detail displayed by this team is commendable. Every aspect of our project, no matter how small, was handled with precision and care. The result is a product that reflects their commitment to excellence."


#-------------------------------
# Faq (Frequently asked questions) Settings
faq:
  enable: false
  faq_title: Frequently asked questions
  faq_intro: Need some answers?
  faq_items:
    - title: What distinguishes you as a mobile developer?
      description: I bring a wealth of experience in crafting seamless user experiences and developing mobile solutions that prioritize functionality and innovation.

#-------------------------------
# Blog Section Settings
blog:
  enable: true
  blog_intro: What’s new?
  blog_title: Latest from blog


#-------------------------------
# Author Section Settings
author_section:
  enable: true
  author_section_title: "Hi there 👋 ! Welcome to my fun zone. I'm Wayne, the ML engineer in the making."
  author_section_description: When I'm not building models or pushing commits, you can catch me at the gym, gaming, watching youtube videos, playing my guitar, or deep in a playlist. Non-career related goals? Get a cool motorcycle, travel to Ethiopia, collect cool art, and learn to do a backflip. If you're working on something cool or just want to connect, let's talk.
  author_section_image: "/images/01-1.jpg"
  author_section_image_alt: Wayne Simmons
  author_section_button_text: Let's сonnect!
  author_section_button_link: "/contact/"


#-------------------------------
# Footer Settings

# Footer Navigation
footer_menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'Projects'
      url: '/projects/'
    - title: 'Posts'
      url: '/posts/'
    - url: '/about/'
      title: 'About Me'

# Social Links
social:
- {icon: "fa-brands fa-linkedin", name: "Linkedin", link: "https://www.linkedin.com/in/wayne-simmons-56808b201/"}
- {icon: "fa-brands fa-github", name: "Github", link: "https://github.com/WayneS0628"}

# Example of adding a new link to the footer - {icon: "fa-brands fa-youtube", name: "Youtube", link: https://youtube.com"}
# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# Newsletter Settings
mailchimp:
  enable: false
  mailchimp_title: Stay inspired weekly 📬 Your friendly dose of tips & insights!
  mailchimp_description: Every Sunday, I deliver actionable tips for enhancing productivity, practical life advice, and top-notch insights gathered from various sources, right to your email inbox.
  mailchimp_identifier: gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
  mailchimp_input_text: Your email address


#-------------------------------
# Contact Settings
contact:
  email: https://formspree.io/f/xaqrowqy # Add your form_id
  description: Lets Chat! # Add a description of your form

# NOTE
# Gerous theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus_identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvod-studio-test


#-------------------------------
# Google Analytics
google_analytics: # Add your GA Tracking Id